### ISSUE TITLE
1:1 채팅방 생성시 로직 개선 및 QueryDsl 개선

### ISSUE THREAD

**Issue by seaStamp** [Just-Clover/YOUng-chat-backend#148]
1:1 채팅방 생성시 해당유저와 기존에 생성된 1:1 채팅방이 있는지 확인하는 부분을 피드백 받고 싶습니다.
JPQL로 해당부분을 짜려고하니 쿼리문이 길어져, QueryDsl로 짰습니다.
기존엔 이 방법말고 다른 방식으로 쿼리문을 짰으나, 예상했던 대로 동작이 안되어 최종적으로 아래와 같이 QueryDsl을 작성했는데,
개선할 수 있는 방법이 있는지 피드백을 받고싶습니다.

그 외에 모든 리뷰도 환영합니다!

https://github.com/Just-Clover/YOUng-chat-backend/blob/96409763e8500b15a45f3affc4cdc257e94db318/src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java#L43-L66

https://github.com/Just-Clover/YOUng-chat-backend/blob/96409763e8500b15a45f3affc4cdc257e94db318/src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java#L16-L36

-------
## 기존에 작성한 쿼리
```java
return queryFactory
        .select(chatroomIdPath)
        .from(chatroomUser)
        .where(chatroomUser.chatroomId.eq(
              JPAExpressions
                    .select(chatroomUser.chatroomId)
                    .from(chatroomUser)
                    .groupBy(chatroomUser.chatroomId)
                    .having(chatroomUser.userId.count().eq(2L))
        ).and(chatroomUser.userId.in(1L, 2L)))
        .fetch();
``` 

**그에 따라서 반영한 QueryDSL**
```java
QChatRoomUser chatRoomUser = QChatRoomUser.chatRoomUser;

ChatRoom chatRoom = queryFactory
    .selectDistinct(chatRoomUser.chatRoom)
    .from(chatRoomUser)
    .where(chatRoomUser.chatRoom.id.eq(
            JPAExpressions
                .select(chatRoomUser.chatRoom.id)
                .from(chatRoomUser)
                .groupBy(chatRoomUser.chatRoom.id)
                .having(chatRoomUser.user.id.count().eq(2L))
        )
        .and(chatRoomUser.user.id.in(userId, friendId))
    )
    .fetchOne();
```
**위의 코드가 동작이 안되는 상황**

1 채팅방에 1,2,3의 유저가 들어가 있고,
2 채팅방에 1,2 유저,
3 채팅방에 1,3 유저가 들어가 있을 때

1,2 유저를 입력값으로 줬을 때 fetchOne 부분에서 하나의 결과가아닌 다수의 결과가 나온다는 에러를 뱉음 or null 값을 뱉음.

**Comment by OuOHoon** [comment]
아래와 같이 해결할 수 있지 않을까 싶어서 코멘트 남깁니다! ChatRoom을 Chat, ChatRoomUser를 ChatUser로 짧게 줄였습니다.
1. Chat, ChatUser를 조인해서 채팅방과 유저 정보를 가져오고
2. group by로 채팅방 id로 묶었을 때,
3. Having 에서 count = 2(2명 참가중인 방) 중에서 찾는 사용자라면 1씩 더해서 2인지 확인
```
SELECT c.*
FROM Chat c
JOIN ChatUser cu ON c.id = cu.chat_id
GROUP BY c.id
HAVING COUNT(cu.chat_id) = 2 AND 
       SUM(CASE WHEN cu.user_id IN (:userId1, :userId2) THEN 1 ELSE 0 END) = 2;
```

**Comment by seaStamp** [comment]
오 3번 방법이면 해결이 가능할 수도있을 것 같네요! 리뷰 감사합니다. 
한번 위의 로직 참고해서 작성해보겠습니다
